### Tests de combat avancés
### Ces tests nécessitent que l'API soit lancée avec des données

@baseUrl = http://localhost:3000/api

### Combat déterministe (Pokémon le plus fort)
POST {{baseUrl}}/battles/deterministic-challenge
Content-Type: application/json

{
  "trainer1Id": 1,
  "trainer2Id": 2
}

### Arène 2 - 100 combats déterministes
POST {{baseUrl}}/battles/arena2
Content-Type: application/json

{
  "trainer1Id": 1,
  "trainer2Id": 2
}

### Créer plus de Pokémon pour des tests plus intéressants
POST {{baseUrl}}/pokemon
Content-Type: application/json

{
  "name": "Squirtle",
  "maxLifePoints": 95,
  "trainerId": 1
}

###
POST {{baseUrl}}/pokemon
Content-Type: application/json

{
  "name": "Bulbasaur",
  "maxLifePoints": 85,
  "trainerId": 2
}

### Enseigner plus d'attaques
POST {{baseUrl}}/attacks
Content-Type: application/json

{
  "name": "Hydro-Pompe",
  "damage": 35,
  "usageLimit": 1
}

###
POST {{baseUrl}}/attacks
Content-Type: application/json

{
  "name": "Fouet-Lianes",
  "damage": 20,
  "usageLimit": 3
}

### Enseigner les nouvelles attaques
POST {{baseUrl}}/pokemon/3/learn-attack/4

###
POST {{baseUrl}}/pokemon/4/learn-attack/5

### Combat avec plus de Pokémon
POST {{baseUrl}}/battles/random-challenge
Content-Type: application/json

{
  "trainer1Id": 1,
  "trainer2Id": 2
}


